// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';
import {main} from '../models';

export function FindFreePort(arg1:number):Promise<number>;

export function InspectPort(arg1:number):Promise<port.PortInfo>;

export function KillPort(arg1:number):Promise<void>;

export function ScanPorts():Promise<Array<main.UIPortInfo>>;

export function SharePort(arg1:number):Promise<string>;

export function StopSharePort(arg1:number):Promise<void>;
