// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindFreePort(arg1) {
  return window['go']['main']['App']['FindFreePort'](arg1);
}

export function InspectPort(arg1) {
  return window['go']['main']['App']['InspectPort'](arg1);
}

export function KillPort(arg1) {
  return window['go']['main']['App']['KillPort'](arg1);
}

export function ScanPorts() {
  return window['go']['main']['App']['ScanPorts']();
}

export function SharePort(arg1) {
  return window['go']['main']['App']['SharePort'](arg1);
}

export function StopSharePort(arg1) {
  return window['go']['main']['App']['StopSharePort'](arg1);
}
