// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {port} from '../models';

export function DeleteRule(arg1:number):Promise<void>;

export function FindFreePort(arg1:number):Promise<number>;

export function GetProcessDetails(arg1:number):Promise<main.ProcessDetails>;

export function GetRules():Promise<Record<number, main.PortRule>>;

export function InspectPort(arg1:number):Promise<port.PortInfo>;

export function KillPort(arg1:number):Promise<void>;

export function SaveRule(arg1:main.PortRule):Promise<void>;

export function ScanPorts():Promise<Array<main.UIPortInfo>>;

export function SharePort(arg1:number):Promise<string>;

export function StartProxy(arg1:number):Promise<number>;

export function StopProxy(arg1:number):Promise<void>;

export function StopSharePort(arg1:number):Promise<void>;
